#![allow(unused_imports)]
use std::mem;

pub enum DebugFlags {
    // COGL_DEBUG_SLICING,
    // COGL_DEBUG_OFFSCREEN,
    // COGL_DEBUG_DRAW,
    // COGL_DEBUG_PANGO,
    // COGL_DEBUG_RECTANGLES,
    // COGL_DEBUG_OBJECT,
    // COGL_DEBUG_BLEND_STRINGS,
    // COGL_DEBUG_DISABLE_BATCHING,
    // COGL_DEBUG_DISABLE_VBOS,
    // COGL_DEBUG_DISABLE_PBOS,
    // COGL_DEBUG_JOURNAL,
    // COGL_DEBUG_BATCHING,
    // COGL_DEBUG_DISABLE_SOFTWARE_TRANSFORM,
    // COGL_DEBUG_MATRICES,
    // COGL_DEBUG_ATLAS,
    // COGL_DEBUG_DUMP_ATLAS_IMAGE,
    // COGL_DEBUG_DISABLE_ATLAS,
    // COGL_DEBUG_DISABLE_SHARED_ATLAS,
    // COGL_DEBUG_OPENGL,
    // COGL_DEBUG_DISABLE_TEXTURING,
    // COGL_DEBUG_DISABLE_ARBFP,
    // COGL_DEBUG_DISABLE_FIXED,
    // COGL_DEBUG_DISABLE_GLSL,
    // COGL_DEBUG_SHOW_SOURCE,
    // COGL_DEBUG_DISABLE_BLENDING,
    // COGL_DEBUG_TEXTURE_PIXMAP,
    // COGL_DEBUG_BITMAP,
    // COGL_DEBUG_DISABLE_NPOT_TEXTURES,
    // COGL_DEBUG_WIREFRAME,
    // COGL_DEBUG_DISABLE_SOFTWARE_CLIP,
    // COGL_DEBUG_DISABLE_PROGRAM_CACHES,
    // COGL_DEBUG_DISABLE_FAST_READ_PIXEL,
    // COGL_DEBUG_CLIPPING,
    // COGL_DEBUG_WINSYS,
    // COGL_DEBUG_PERFORMANCE,
  
    // COGL_DEBUG_N_FLAGS
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct DebugObjectTypeInfo<'a> {
    pub name: &'a str, // TODO: may be Option<String>, see gdk::WindowAttr
    pub instance_count: u64,
}

